const ADD_USER = 'ADD_USER';
const DELETE_USER = 'DELETE_USER';
const SELECT_USER = 'SELECT_USER';
const UPDATE_USER = 'UPDATE_USER';

export {
    ADD_USER,
    DELETE_USER,
    SELECT_USER,
    UPDATE_USER,    
}